import type { FailureType } from "./schemas";
import { taxonomyEntrySchema } from "./schemas";

export const failureTaxonomy = [
  {
    id: "MISSING_ENV_VAR",
    label: "Missing environment variable",
    description: "The build or runtime expects an environment variable that is unset in Vercel.",
    symptoms: ["process.env access throws", "Missing required environment variable", "env validation failure"],
    likelyCauses: ["Variable exists locally but not in Vercel", "Preview/production scopes differ", "Public variable prefix is missing"],
    fixSteps: ["Add the missing variable in Vercel Project Settings", "Confirm preview and production scopes", "Rebuild after the variable is saved"],
    verificationCommands: ["npm run build", "vercel env ls", "vercel --prod"],
    preventionChecks: ["Keep .env.example complete", "Validate env at boot with safe error messages", "Document variable scope"],
  },
  {
    id: "TYPESCRIPT_ERROR",
    label: "TypeScript compile error",
    description: "The Next.js build failed during type checking or transpilation.",
    symptoms: ["Type error:", "Property does not exist", "Type is not assignable"],
    likelyCauses: ["Stale interface", "Incorrect component props", "Unchecked API response shape"],
    fixSteps: ["Open the referenced file and align the type contract", "Add a narrow guard or schema parse", "Run typecheck before redeploying"],
    verificationCommands: ["npm run typecheck", "npm run build"],
    preventionChecks: ["Keep strict TypeScript enabled", "Test representative component props", "Validate external data with schemas"],
  },
  {
    id: "MODULE_NOT_FOUND",
    label: "Module not found",
    description: "The bundler cannot resolve an import or package.",
    symptoms: ["Module not found", "Can't resolve", "Cannot find module"],
    likelyCauses: ["Dependency missing from package.json", "Incorrect import casing", "Path alias mismatch"],
    fixSteps: ["Install or add the dependency", "Fix import path casing", "Verify tsconfig path aliases"],
    verificationCommands: ["npm install", "npm run build"],
    preventionChecks: ["Run clean installs in CI", "Avoid case-only path differences", "Keep lockfile committed"],
  },
  {
    id: "NEXT_BUILD_ERROR",
    label: "Next.js build or route error",
    description: "Next.js detected an invalid route, server/client boundary issue, or dynamic rendering violation.",
    symptoms: ["Dynamic server usage", "Failed to collect page data", "useSearchParams should be wrapped"],
    likelyCauses: ["Dynamic API used in static route", "Server-only code imported into client component", "Route handler throws during build"],
    fixSteps: ["Move dynamic work behind a route handler or server boundary", "Mark the route dynamic when appropriate", "Guard build-time data access"],
    verificationCommands: ["npm run build"],
    preventionChecks: ["Smoke test production builds locally", "Keep server/client boundaries explicit", "Avoid build-time secret reads in pages"],
  },
  {
    id: "PACKAGE_INSTALL_ERROR",
    label: "Package install error",
    description: "Install failed before the app could build.",
    symptoms: ["ERESOLVE", "npm ERR!", "peer dependency", "lockfile"],
    likelyCauses: ["Peer dependency conflict", "Stale lockfile", "Unsupported Node/npm version"],
    fixSteps: ["Resolve the peer dependency range", "Regenerate the lockfile with the project package manager", "Pin Node version if needed"],
    verificationCommands: ["npm install", "npm run build"],
    preventionChecks: ["Commit lockfiles", "Document Node version", "Avoid mixing package managers"],
  },
  {
    id: "PRISMA_DATABASE_ERROR",
    label: "Prisma database configuration error",
    description: "Prisma failed because database configuration or generation is missing.",
    symptoms: ["PrismaClientInitializationError", "DATABASE_URL", "prisma generate"],
    likelyCauses: ["Invalid DATABASE_URL", "Prisma client not generated", "Database unavailable during build"],
    fixSteps: ["Validate DATABASE_URL in Vercel env", "Run prisma generate during build if needed", "Avoid live DB queries at build time"],
    verificationCommands: ["npx prisma validate", "npx prisma generate", "npm run build"],
    preventionChecks: ["Use pooled production URLs", "Keep migrations separate from builds", "Redact database URLs in logs"],
  },
  {
    id: "SUPABASE_CONFIG_ERROR",
    label: "Supabase configuration error",
    description: "Supabase client setup is missing required project URL or anon/service key values.",
    symptoms: ["supabaseUrl is required", "NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_ANON_KEY"],
    likelyCauses: ["Missing public Supabase URL", "Wrong env scope", "Using service key in client code"],
    fixSteps: ["Add public URL and anon key to the correct Vercel scope", "Keep service-role keys server-only", "Rebuild after updating env"],
    verificationCommands: ["npm run build", "vercel env ls"],
    preventionChecks: ["Separate public and server env names", "Never expose service-role keys", "Add env schema tests"],
  },
  {
    id: "STRIPE_WEBHOOK_ERROR",
    label: "Stripe webhook configuration error",
    description: "Stripe webhook verification cannot run because the signing secret or route config is wrong.",
    symptoms: ["STRIPE_WEBHOOK_SECRET", "No signatures found", "webhook secret missing"],
    likelyCauses: ["Webhook secret missing in Vercel", "Raw body not preserved", "Wrong endpoint secret for environment"],
    fixSteps: ["Add STRIPE_WEBHOOK_SECRET to Vercel", "Verify the route uses raw body where required", "Use test/live secrets in matching environments"],
    verificationCommands: ["npm run build", "stripe listen --forward-to localhost:3000/api/webhooks/stripe"],
    preventionChecks: ["Document test vs live webhook secrets", "Never log webhook secrets", "Add route-level webhook tests"],
  },
  {
    id: "VERCEL_RUNTIME_ERROR",
    label: "Vercel runtime mismatch",
    description: "A route or function uses APIs incompatible with the selected Vercel runtime.",
    symptoms: ["Edge Runtime", "Node.js APIs are not available", "Function Runtimes must have a valid version"],
    likelyCauses: ["Node-only package imported in Edge runtime", "Unsupported runtime setting", "Function exceeds runtime limits"],
    fixSteps: ["Switch route runtime to nodejs or remove Node-only APIs", "Check vercel.json function settings", "Redeploy after runtime alignment"],
    verificationCommands: ["npm run build", "vercel --prod"],
    preventionChecks: ["Declare route runtime intentionally", "Keep runtime-specific packages isolated", "Review Vercel function limits"],
  },
  {
    id: "OUT_OF_MEMORY",
    label: "Build timeout or memory pressure",
    description: "The build or serverless function exceeded memory or duration limits.",
    symptoms: ["JavaScript heap out of memory", "timed out", "exceeded memory limit"],
    likelyCauses: ["Large static generation workload", "Unbounded build-time data fetch", "Bundle or image processing spike"],
    fixSteps: ["Reduce build-time work", "Paginate or cache data generation", "Inspect bundle and function size"],
    verificationCommands: ["npm run build", "NODE_OPTIONS=--max_old_space_size=4096 npm run build"],
    preventionChecks: ["Track build duration", "Avoid unbounded static generation", "Monitor function memory"],
  },
  {
    id: "UNKNOWN",
    label: "Unknown failure",
    description: "The log does not match a known deterministic failure pattern.",
    symptoms: ["Unclassified error lines"],
    likelyCauses: ["Insufficient log detail", "New framework or provider error", "Multiple overlapping failures"],
    fixSteps: ["Collect full build logs", "Search for the first fatal error", "Re-run with verbose logging"],
    verificationCommands: ["npm run build"],
    preventionChecks: ["Keep structured logs", "Capture build command and environment", "Add new recipe after triage"],
  },
] satisfies Array<ReturnType<typeof taxonomyEntrySchema.parse>>;

export const taxonomyById = Object.fromEntries(
  failureTaxonomy.map((entry) => [entry.id, entry]),
) as Record<FailureType, (typeof failureTaxonomy)[number]>;
